//! 中文：Invoke 请求与响应的数据契约。
//! English: Invoke request and response contracts.

use crate::capability::CapabilityName;
use crate::error::EvaError;
use crate::event::{EventPayload, TraceContext};
use crate::ids::{AdapterId, AgentId, GenerationId, RequestId};
use std::time::Duration;

/// 中文：Invoke 请求的目标。
/// English: Target of an invoke request.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum InvokeTarget {
    /// 中文：调用指定 Agent。
    /// English: Invoke a specific Agent.
    Agent(
        /// 接收调用的 Agent 稳定标识。
        AgentId,
    ),
    /// 中文：调用命名 Capability，由上层路由决定 provider。
    /// English: Invoke a named Capability; upper routing decides the provider.
    Capability(
        /// 交由上层路由选择 provider 的 Capability 名称。
        CapabilityName,
    ),
    /// 中文：调用指定 Adapter。
    /// English: Invoke a specific Adapter.
    Adapter(
        /// 接收调用的 Adapter 稳定标识。
        AdapterId,
    ),
}

/// 中文：不透明 invoke 输入；复用 EventPayload 以保持事件与调用通道 payload 一致。
/// English: Opaque invoke input; reuses EventPayload to keep event and invoke channel payloads consistent.
pub type InvokeInput = EventPayload;

/// 中文：不透明 invoke 输出；schema 解释属于执行方或调用方。
/// English: Opaque invoke output; schema interpretation belongs to the executor or caller.
pub type InvokeOutput = EventPayload;

/// 中文：控制 invoke 请求的非业务 metadata。
/// English: Non-business metadata controlling an invoke request.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct InvokeMetadata {
    // 中文：timeout 只是调用预算声明，真正计时和取消由 runtime 执行。
    // English: timeout is only a call budget declaration; runtime performs actual timing and cancellation.
    timeout: Option<Duration>,
    // 中文：trace 将 invoke 与事件链路关联起来。
    // English: trace links invokes with event chains.
    trace: TraceContext,
    // 中文：generation_id 用于运行时热更新/代际隔离。
    // English: generation_id is used for runtime hot-reload and generation isolation.
    generation_id: Option<GenerationId>,
    // 中文：caller 标识发起调用的 Agent，不等同于认证身份。
    // English: caller identifies the Agent that initiated the invoke and is not an authentication identity.
    caller: Option<AgentId>,
}

impl InvokeMetadata {
    /// 中文：创建空 metadata。
    /// English: Creates empty metadata.
    pub fn new() -> Self {
        Self::default()
    }

    /// 中文：存在时返回 timeout budget。
    /// English: Returns the timeout budget, when present.
    pub fn timeout(&self) -> Option<Duration> {
        self.timeout
    }

    /// 中文：返回 trace context。
    /// English: Returns trace context.
    pub fn trace(&self) -> &TraceContext {
        &self.trace
    }

    /// 中文：存在时返回 generation id。
    /// English: Returns the generation id, when present.
    pub fn generation_id(&self) -> Option<&GenerationId> {
        self.generation_id.as_ref()
    }

    /// 中文：存在时返回调用方 Agent id。
    /// English: Returns the calling Agent id, when present.
    pub fn caller(&self) -> Option<&AgentId> {
        self.caller.as_ref()
    }

    /// 中文：设置 timeout budget。
    /// English: Sets the timeout budget.
    pub fn with_timeout(mut self, timeout: Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// 中文：设置 trace context。
    /// English: Sets trace context.
    pub fn with_trace(mut self, trace: TraceContext) -> Self {
        self.trace = trace;
        self
    }

    /// 中文：设置 generation id。
    /// English: Sets generation id.
    pub fn with_generation_id(mut self, generation_id: GenerationId) -> Self {
        self.generation_id = Some(generation_id);
        self
    }

    /// 中文：设置调用方 Agent id。
    /// English: Sets the calling Agent id.
    pub fn with_caller(mut self, caller: AgentId) -> Self {
        self.caller = Some(caller);
        self
    }
}

/// 中文：调用 Agent、Capability 或 Adapter 的请求。
/// English: A request to invoke an Agent, Capability, or Adapter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InvokeRequest {
    // 中文：request_id 由上层生成，用于关联 response、日志和事件。
    // English: request_id is generated by upper layers to correlate responses, logs, and events.
    request_id: RequestId,
    // 中文：target 描述调用对象，不包含执行策略。
    // English: target names what is invoked and does not include execution strategy.
    target: InvokeTarget,
    // 中文：input 保持不透明，eva-core 不解析业务协议。
    // English: input stays opaque; eva-core does not parse business protocols.
    input: InvokeInput,
    // 中文：metadata 承载 timeout、trace、generation 和 caller 等非业务信息。
    // English: metadata carries non-business timeout, trace, generation, and caller data.
    metadata: InvokeMetadata,
}

impl InvokeRequest {
    /// 中文：使用默认 metadata 创建 invoke 请求。
    /// English: Creates an invoke request with default metadata.
    pub fn new(request_id: RequestId, target: InvokeTarget, input: InvokeInput) -> Self {
        Self {
            request_id,
            target,
            input,
            metadata: InvokeMetadata::new(),
        }
    }

    /// 中文：返回 request id。
    /// English: Returns the request id.
    pub fn request_id(&self) -> &RequestId {
        &self.request_id
    }

    /// 中文：返回 invoke 目标。
    /// English: Returns the invoke target.
    pub fn target(&self) -> &InvokeTarget {
        &self.target
    }

    /// 中文：返回不透明输入 payload。
    /// English: Returns the opaque input payload.
    pub fn input(&self) -> &InvokeInput {
        &self.input
    }

    /// 中文：返回 metadata。
    /// English: Returns metadata.
    pub fn metadata(&self) -> &InvokeMetadata {
        &self.metadata
    }

    /// 中文：整体替换 metadata。
    /// English: Replaces metadata.
    pub fn with_metadata(mut self, metadata: InvokeMetadata) -> Self {
        self.metadata = metadata;
        self
    }
}

/// 中文：Invoke 响应的生命周期状态。
/// English: Lifecycle status of an invoke response.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum InvokeStatus {
    /// 中文：Runtime 已接受请求，结果将通过其他路径返回。
    /// English: Runtime accepted the request, with result to follow through another path.
    Accepted,
    /// 中文：请求成功完成。
    /// English: Request completed successfully.
    Completed,
    /// 中文：请求失败并携带错误。
    /// English: Request failed with an error.
    Failed,
    /// 中文：请求已取消。
    /// English: Request was cancelled.
    Cancelled,
    /// 中文：请求超过 timeout。
    /// English: Request exceeded its timeout.
    Timeout,
}

impl InvokeStatus {
    /// 中文：终态状态返回 true。
    /// English: Returns true for terminal statuses.
    pub fn is_terminal(self) -> bool {
        matches!(
            self,
            Self::Completed | Self::Failed | Self::Cancelled | Self::Timeout
        )
    }
}

/// 中文：Invoke 请求的结果。
/// English: Result of an invoke request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InvokeResponse {
    // 中文：response 必须回指原 request，方便异步和日志关联。
    // English: A response must point back to its request for async and log correlation.
    request_id: RequestId,
    // 中文：status 是机器可读生命周期状态。
    // English: status is the machine-readable lifecycle state.
    status: InvokeStatus,
    // 中文：只有成功完成时通常携带 output。
    // English: output is normally present only for completed responses.
    output: Option<InvokeOutput>,
    // 中文：失败、取消或 timeout 时携带结构化错误。
    // English: failed, cancelled, or timeout responses carry structured errors.
    error: Option<EvaError>,
    // 中文：response metadata 用于继续传播 trace/generation 等上下文。
    // English: response metadata continues trace/generation context propagation.
    metadata: InvokeMetadata,
}

impl InvokeResponse {
    /// 中文：创建 accepted 响应。
    /// English: Creates an accepted response.
    pub fn accepted(request_id: RequestId) -> Self {
        Self::new(request_id, InvokeStatus::Accepted, None, None)
    }

    /// 中文：创建带 output 的 completed 响应。
    /// English: Creates a completed response with output.
    pub fn completed(request_id: RequestId, output: InvokeOutput) -> Self {
        Self::new(request_id, InvokeStatus::Completed, Some(output), None)
    }

    /// 中文：创建带结构化错误的 failed 响应。
    /// English: Creates a failed response with a structured error.
    pub fn failed(request_id: RequestId, error: EvaError) -> Self {
        Self::new(request_id, InvokeStatus::Failed, None, Some(error))
    }

    /// 中文：创建 cancelled 响应；可传入结构化取消原因。
    /// English: Creates a cancelled response; a reason may be supplied as a structured error.
    pub fn cancelled(request_id: RequestId, reason: Option<EvaError>) -> Self {
        // 中文：即使调用方未给 reason，也保留默认错误，避免取消状态没有可诊断信息。
        // English: Preserve a default error when no reason is supplied so cancellation stays diagnosable.
        let error = reason.or_else(|| Some(EvaError::conflict("invoke request was cancelled")));
        Self::new(request_id, InvokeStatus::Cancelled, None, error)
    }

    /// 中文：创建 timeout 响应。
    /// English: Creates a timeout response.
    pub fn timeout(request_id: RequestId, message: impl Into<String>) -> Self {
        Self::new(
            request_id,
            InvokeStatus::Timeout,
            None,
            Some(EvaError::timeout(message)),
        )
    }

    /// 创建保留既有结构化错误的 timeout 响应，供 provider code 和诊断上下文透传。
    pub fn timeout_with_error(request_id: RequestId, error: EvaError) -> Self {
        Self::new(request_id, InvokeStatus::Timeout, None, Some(error))
    }

    /// 汇总所有响应状态的公共构造路径，确保 metadata 始终存在且输出、错误由状态构造器约束。
    fn new(
        request_id: RequestId,
        status: InvokeStatus,
        output: Option<InvokeOutput>,
        error: Option<EvaError>,
    ) -> Self {
        Self {
            request_id,
            status,
            output,
            error,
            metadata: InvokeMetadata::new(),
        }
    }

    /// 中文：返回该 response 所属的 request id。
    /// English: Returns the request id this response belongs to.
    pub fn request_id(&self) -> &RequestId {
        &self.request_id
    }

    /// 中文：返回 response 状态。
    /// English: Returns response status.
    pub fn status(&self) -> InvokeStatus {
        self.status
    }

    /// 中文：存在 output 时返回它。
    /// English: Returns output, when present.
    pub fn output(&self) -> Option<&InvokeOutput> {
        self.output.as_ref()
    }

    /// 中文：存在 error 时返回它。
    /// English: Returns error, when present.
    pub fn error(&self) -> Option<&EvaError> {
        self.error.as_ref()
    }

    /// 中文：返回 metadata。
    /// English: Returns metadata.
    pub fn metadata(&self) -> &InvokeMetadata {
        &self.metadata
    }

    /// 中文：整体替换 metadata。
    /// English: Replaces metadata.
    pub fn with_metadata(mut self, metadata: InvokeMetadata) -> Self {
        self.metadata = metadata;
        self
    }

    /// 中文：仅 completed 响应返回 true。
    /// English: Returns true only for completed responses.
    pub fn is_success(&self) -> bool {
        self.status == InvokeStatus::Completed
    }
}

#[cfg(test)]
/// Invoke 请求、终态和结构化失败语义的回归测试。
mod tests {
    use super::*;

    /// 将测试文本转换为已校验请求 ID。
    fn request_id(value: &str) -> RequestId {
        RequestId::parse(value).unwrap()
    }

    #[test]
    /// 验证 invoke 请求必须携带明确目标，并保留输入数据。
    fn invoke_request_requires_target() {
        let target = InvokeTarget::Agent(AgentId::parse("agent-root").unwrap());
        let request = InvokeRequest::new(request_id("req-1"), target, InvokeInput::text("run"));

        assert_eq!(request.request_id().as_str(), "req-1");
        assert!(matches!(request.target(), InvokeTarget::Agent(_)));
        assert_eq!(request.input().as_text(), Some("run"));
    }

    #[test]
    /// 验证 timeout、代际和调用方等调度 metadata 可附加到请求。
    fn invoke_request_accepts_metadata() {
        let target = InvokeTarget::Capability(CapabilityName::parse("repo.summary").unwrap());
        let metadata = InvokeMetadata::new()
            .with_timeout(Duration::from_secs(5))
            .with_generation_id(GenerationId::parse("gen-1").unwrap())
            .with_caller(AgentId::parse("agent-root").unwrap());
        let request = InvokeRequest::new(request_id("req-1"), target, InvokeInput::empty())
            .with_metadata(metadata);

        assert_eq!(request.metadata().timeout(), Some(Duration::from_secs(5)));
        assert_eq!(
            request.metadata().generation_id().unwrap().as_str(),
            "gen-1"
        );
        assert_eq!(request.metadata().caller().unwrap().as_str(), "agent-root");
    }

    #[test]
    /// 验证 completed 是唯一成功终态且携带输出。
    fn completed_response_is_success() {
        let response = InvokeResponse::completed(request_id("req-1"), InvokeOutput::text("ok"));

        assert_eq!(response.status(), InvokeStatus::Completed);
        assert!(response.is_success());
        assert!(response.status().is_terminal());
        assert_eq!(response.output().unwrap().as_text(), Some("ok"));
    }

    #[test]
    /// 验证 accepted 仅表示已接收，不能被误判为成功终态。
    fn accepted_response_is_not_terminal() {
        let response = InvokeResponse::accepted(request_id("req-1"));

        assert_eq!(response.status(), InvokeStatus::Accepted);
        assert!(!response.is_success());
        assert!(!response.status().is_terminal());
        assert!(response.output().is_none());
    }

    #[test]
    /// 验证 failed 响应保留原始结构化错误并标记为终态。
    fn failed_response_carries_error() {
        let error = EvaError::not_found("missing agent");
        let response = InvokeResponse::failed(request_id("req-1"), error.clone());

        assert_eq!(response.status(), InvokeStatus::Failed);
        assert_eq!(response.error(), Some(&error));
        assert!(response.status().is_terminal());
    }

    #[test]
    /// 验证 timeout 是可重试的终态并始终携带诊断错误。
    fn timeout_response_is_terminal() {
        let response = InvokeResponse::timeout(request_id("req-1"), "agent timed out");

        assert_eq!(response.status(), InvokeStatus::Timeout);
        assert!(response.status().is_terminal());
        assert!(response.error().unwrap().is_retryable());
    }

    #[test]
    /// 验证 timeout 构造器不会丢失 provider code 与上下文字段。
    fn timeout_response_can_preserve_structured_error_context() {
        let error = EvaError::timeout("provider timed out")
            .with_provider_code("adapter_status_timeout")
            .with_context("provider", "codex-cli");

        let response = InvokeResponse::timeout_with_error(request_id("req-1"), error.clone());

        assert_eq!(response.status(), InvokeStatus::Timeout);
        assert_eq!(response.error(), Some(&error));
    }

    #[test]
    /// 验证取消未提供原因时仍生成可诊断的默认错误。
    fn cancelled_response_carries_default_reason() {
        let response = InvokeResponse::cancelled(request_id("req-1"), None);

        assert_eq!(response.status(), InvokeStatus::Cancelled);
        assert!(response.status().is_terminal());
        assert!(response.error().is_some());
    }

    #[test]
    /// 验证 invoke 协议可区分 Agent、Capability 与 Adapter 三类目标。
    fn invoke_target_supports_agent_capability_and_adapter() {
        let agent = InvokeTarget::Agent(AgentId::parse("agent-root").unwrap());
        let capability = InvokeTarget::Capability(CapabilityName::parse("repo.summary").unwrap());
        let adapter = InvokeTarget::Adapter(AdapterId::parse("adapter-cli").unwrap());

        assert!(matches!(agent, InvokeTarget::Agent(_)));
        assert!(matches!(capability, InvokeTarget::Capability(_)));
        assert!(matches!(adapter, InvokeTarget::Adapter(_)));
    }
}
