//! MCP compatibility measurement release-evidence contract.

use crate::checklist::ReleaseGateStatus;
use eva_core::EvaError;

/// Canonical subject format emitted by the sealed MCP measurement producer.
pub const MCP_COMPATIBILITY_EVIDENCE_FORMAT: &str = "eva.mcp-compatibility.v1";

const FIELD_ORDER: [&str; 24] = [
    "format",
    "evidence_kind",
    "server_name",
    "server_version",
    "protocol_version",
    "transport",
    "tls_handshake_completed",
    "tls_peer_name",
    "tls_protocol",
    "tls_handshake_count",
    "tool_name",
    "schema_sha256",
    "schema_bytes",
    "output_sha256",
    "output_bytes",
    "initialize_server_info_observed",
    "tools_list_schema_observed",
    "tools_call_result_observed",
    "abort_socket_closed",
    "abort_session_deleted",
    "abort_reader_joined",
    "abort_sessions_after",
    "abort_readers_after",
    "abort_cleanup_pending_after",
];

/// Parsed, canonical projection of one sealed MCP compatibility run.
///
/// This type intentionally has no public field-by-field constructor. Production trust comes from
/// the independently verified `EvidenceEnvelope`; parsing this document never upgrades its kind.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReleaseMcpCompatibilityEvidence {
    /// Producer-owned format marker.
    pub format: String,
    /// Must remain `measurement`; the trusted envelope independently proves the evidence kind.
    pub evidence_kind: String,
    /// Directly observed initialize server name.
    pub server_name: String,
    /// Directly observed initialize server version.
    pub server_version: String,
    /// Directly observed MCP protocol version.
    pub protocol_version: String,
    /// Transport exercised by the run.
    pub transport: String,
    /// Whether rustls completed a real handshake.
    pub tls_handshake_completed: bool,
    /// Peer name passed to rustls verification.
    pub tls_peer_name: String,
    /// Negotiated rustls protocol.
    pub tls_protocol: String,
    /// Number of real TLS handshakes observed by the bounded scenario.
    pub tls_handshake_count: u64,
    /// Tool selected by the explicit server allow-list.
    pub tool_name: String,
    /// Digest of the exact schema bytes; raw schema is intentionally excluded.
    pub schema_sha256: String,
    /// Number of bytes covered by `schema_sha256`.
    pub schema_bytes: u64,
    /// Digest of the exact call-result bytes; raw output is intentionally excluded.
    pub output_sha256: String,
    /// Number of bytes covered by `output_sha256`.
    pub output_bytes: u64,
    /// Direct initialize/serverInfo observation.
    pub initialize_server_info_observed: bool,
    /// Direct tools/list schema observation.
    pub tools_list_schema_observed: bool,
    /// Direct tools/call result observation.
    pub tools_call_result_observed: bool,
    /// Typed abort receipt: client socket was closed.
    pub abort_socket_closed: bool,
    /// Typed abort receipt: MCP session DELETE completed.
    pub abort_session_deleted: bool,
    /// Typed abort receipt: stream reader joined.
    pub abort_reader_joined: bool,
    /// Registered sessions remaining after abort.
    pub abort_sessions_after: u32,
    /// Stream readers remaining after abort.
    pub abort_readers_after: u32,
    /// Cleanup work remaining after abort.
    pub abort_cleanup_pending_after: u32,
}

/// Consumer-owned verification of a canonical MCP compatibility measurement.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReleaseMcpCompatibilityVerificationReport {
    /// `verified` or `blocked`.
    pub status: String,
    /// Stable failures generated by consumer policy.
    pub failures: Vec<String>,
    /// Path-free facts safe to expose in release output.
    pub audit: Vec<String>,
}

impl ReleaseMcpCompatibilityEvidence {
    /// Parse the exact LF-terminated canonical subject emitted by the measurement producer.
    pub fn parse_manifest(data: &str) -> Result<Self, EvaError> {
        if !data.is_ascii() || data.contains('\r') || !data.ends_with('\n') {
            return Err(EvaError::invalid_argument(
                "MCP compatibility evidence must be canonical ASCII with LF termination",
            ));
        }
        let lines = data[..data.len() - 1].split('\n').collect::<Vec<_>>();
        if lines.len() != FIELD_ORDER.len() {
            return Err(EvaError::invalid_argument(
                "MCP compatibility evidence field count is invalid",
            )
            .with_context("field_count", lines.len().to_string()));
        }

        let mut values = Vec::with_capacity(FIELD_ORDER.len());
        for (line, expected_key) in lines.iter().zip(FIELD_ORDER) {
            let (key, value) = line.split_once('=').ok_or_else(|| {
                EvaError::invalid_argument("MCP compatibility evidence field is malformed")
                    .with_context("field", expected_key)
            })?;
            if key != expected_key || value.is_empty() || value.contains('=') {
                return Err(EvaError::invalid_argument(
                    "MCP compatibility evidence fields are not canonical",
                )
                .with_context("expected_field", expected_key)
                .with_context("actual_field", key));
            }
            values.push(value);
        }

        let evidence = Self {
            format: values[0].to_owned(),
            evidence_kind: values[1].to_owned(),
            server_name: values[2].to_owned(),
            server_version: values[3].to_owned(),
            protocol_version: values[4].to_owned(),
            transport: values[5].to_owned(),
            tls_handshake_completed: parse_bool("tls_handshake_completed", values[6])?,
            tls_peer_name: values[7].to_owned(),
            tls_protocol: values[8].to_owned(),
            tls_handshake_count: parse_u64("tls_handshake_count", values[9])?,
            tool_name: values[10].to_owned(),
            schema_sha256: parse_digest("schema_sha256", values[11])?,
            schema_bytes: parse_u64("schema_bytes", values[12])?,
            output_sha256: parse_digest("output_sha256", values[13])?,
            output_bytes: parse_u64("output_bytes", values[14])?,
            initialize_server_info_observed: parse_bool(
                "initialize_server_info_observed",
                values[15],
            )?,
            tools_list_schema_observed: parse_bool("tools_list_schema_observed", values[16])?,
            tools_call_result_observed: parse_bool("tools_call_result_observed", values[17])?,
            abort_socket_closed: parse_bool("abort_socket_closed", values[18])?,
            abort_session_deleted: parse_bool("abort_session_deleted", values[19])?,
            abort_reader_joined: parse_bool("abort_reader_joined", values[20])?,
            abort_sessions_after: parse_u32("abort_sessions_after", values[21])?,
            abort_readers_after: parse_u32("abort_readers_after", values[22])?,
            abort_cleanup_pending_after: parse_u32("abort_cleanup_pending_after", values[23])?,
        };
        if evidence.to_manifest() != data {
            return Err(EvaError::invalid_argument(
                "MCP compatibility evidence manifest is not canonical",
            ));
        }
        Ok(evidence)
    }

    /// Serialize the exact bytes bound by the release evidence envelope.
    pub fn to_manifest(&self) -> String {
        format!(
            concat!(
                "format={}\n",
                "evidence_kind={}\n",
                "server_name={}\n",
                "server_version={}\n",
                "protocol_version={}\n",
                "transport={}\n",
                "tls_handshake_completed={}\n",
                "tls_peer_name={}\n",
                "tls_protocol={}\n",
                "tls_handshake_count={}\n",
                "tool_name={}\n",
                "schema_sha256={}\n",
                "schema_bytes={}\n",
                "output_sha256={}\n",
                "output_bytes={}\n",
                "initialize_server_info_observed={}\n",
                "tools_list_schema_observed={}\n",
                "tools_call_result_observed={}\n",
                "abort_socket_closed={}\n",
                "abort_session_deleted={}\n",
                "abort_reader_joined={}\n",
                "abort_sessions_after={}\n",
                "abort_readers_after={}\n",
                "abort_cleanup_pending_after={}\n"
            ),
            self.format,
            self.evidence_kind,
            self.server_name,
            self.server_version,
            self.protocol_version,
            self.transport,
            self.tls_handshake_completed,
            self.tls_peer_name,
            self.tls_protocol,
            self.tls_handshake_count,
            self.tool_name,
            self.schema_sha256,
            self.schema_bytes,
            self.output_sha256,
            self.output_bytes,
            self.initialize_server_info_observed,
            self.tools_list_schema_observed,
            self.tools_call_result_observed,
            self.abort_socket_closed,
            self.abort_session_deleted,
            self.abort_reader_joined,
            self.abort_sessions_after,
            self.abort_readers_after,
            self.abort_cleanup_pending_after,
        )
    }

    /// Apply release-consumer policy to direct observations and the typed abort receipt.
    pub fn verify(&self) -> ReleaseMcpCompatibilityVerificationReport {
        let mut failures = Vec::new();
        require_equal(
            &mut failures,
            "format",
            &self.format,
            MCP_COMPATIBILITY_EVIDENCE_FORMAT,
        );
        require_equal(
            &mut failures,
            "evidence_kind",
            &self.evidence_kind,
            "measurement",
        );
        require_equal(&mut failures, "server_name", &self.server_name, "eva");
        require_equal(
            &mut failures,
            "server_version",
            &self.server_version,
            env!("CARGO_PKG_VERSION"),
        );
        require_equal(
            &mut failures,
            "protocol_version",
            &self.protocol_version,
            "2025-11-25",
        );
        require_equal(
            &mut failures,
            "transport",
            &self.transport,
            "streamable_http",
        );
        require_true(
            &mut failures,
            "tls_handshake_completed",
            self.tls_handshake_completed,
        );
        require_equal(
            &mut failures,
            "tls_peer_name",
            &self.tls_peer_name,
            "127.0.0.1",
        );
        if !matches!(self.tls_protocol.as_str(), "TLSv1_2" | "TLSv1_3") {
            failures.push("tls_protocol:unsupported".to_owned());
        }
        if self.tls_handshake_count == 0 {
            failures.push("tls_handshake_count:empty".to_owned());
        }
        require_equal(&mut failures, "tool_name", &self.tool_name, "compat.echo");
        if self.schema_bytes == 0 {
            failures.push("schema_bytes:empty".to_owned());
        }
        if self.output_bytes == 0 {
            failures.push("output_bytes:empty".to_owned());
        }
        require_true(
            &mut failures,
            "initialize_server_info_observed",
            self.initialize_server_info_observed,
        );
        require_true(
            &mut failures,
            "tools_list_schema_observed",
            self.tools_list_schema_observed,
        );
        require_true(
            &mut failures,
            "tools_call_result_observed",
            self.tools_call_result_observed,
        );
        require_true(
            &mut failures,
            "abort_socket_closed",
            self.abort_socket_closed,
        );
        require_true(
            &mut failures,
            "abort_session_deleted",
            self.abort_session_deleted,
        );
        require_true(
            &mut failures,
            "abort_reader_joined",
            self.abort_reader_joined,
        );
        require_zero(
            &mut failures,
            "abort_sessions_after",
            self.abort_sessions_after,
        );
        require_zero(
            &mut failures,
            "abort_readers_after",
            self.abort_readers_after,
        );
        require_zero(
            &mut failures,
            "abort_cleanup_pending_after",
            self.abort_cleanup_pending_after,
        );

        ReleaseMcpCompatibilityVerificationReport {
            status: if failures.is_empty() {
                "verified"
            } else {
                "blocked"
            }
            .to_owned(),
            failures,
            audit: vec![
                format!("mcp.server:{}@{}", self.server_name, self.server_version),
                format!("mcp.protocol_version:{}", self.protocol_version),
                format!("mcp.transport:{}", self.transport),
                format!("mcp.tls_protocol:{}", self.tls_protocol),
                format!("mcp.tls_handshake_count:{}", self.tls_handshake_count),
                format!("mcp.tool:{}", self.tool_name),
                format!("mcp.schema_digest:{}", self.schema_sha256),
                format!("mcp.schema_bytes:{}", self.schema_bytes),
                format!("mcp.output_digest:{}", self.output_sha256),
                format!("mcp.output_bytes:{}", self.output_bytes),
                format!(
                    "mcp.abort_residuals:sessions={},readers={},cleanup_pending={}",
                    self.abort_sessions_after,
                    self.abort_readers_after,
                    self.abort_cleanup_pending_after
                ),
            ],
        }
    }
}

impl ReleaseMcpCompatibilityVerificationReport {
    /// Convert verification outcome to the shared release gate status.
    pub fn gate_status(&self) -> ReleaseGateStatus {
        if self.status == "verified" {
            ReleaseGateStatus::Pass
        } else {
            ReleaseGateStatus::Blocked
        }
    }
}

fn parse_bool(field: &str, value: &str) -> Result<bool, EvaError> {
    match value {
        "true" => Ok(true),
        "false" => Ok(false),
        _ => Err(
            EvaError::invalid_argument("MCP compatibility evidence boolean is invalid")
                .with_context("field", field),
        ),
    }
}

fn parse_u64(field: &str, value: &str) -> Result<u64, EvaError> {
    if value != "0" && value.starts_with('0') {
        return Err(EvaError::invalid_argument(
            "MCP compatibility evidence integer is not canonical",
        )
        .with_context("field", field));
    }
    value.parse::<u64>().map_err(|_| {
        EvaError::invalid_argument("MCP compatibility evidence integer is invalid")
            .with_context("field", field)
    })
}

fn parse_u32(field: &str, value: &str) -> Result<u32, EvaError> {
    parse_u64(field, value).and_then(|value| {
        u32::try_from(value).map_err(|_| {
            EvaError::invalid_argument("MCP compatibility evidence integer is out of range")
                .with_context("field", field)
        })
    })
}

fn parse_digest(field: &str, value: &str) -> Result<String, EvaError> {
    let Some(hex) = value.strip_prefix("sha256:") else {
        return Err(EvaError::invalid_argument(
            "MCP compatibility evidence digest must use sha256",
        )
        .with_context("field", field));
    };
    if hex.len() != 64
        || !hex
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    {
        return Err(EvaError::invalid_argument(
            "MCP compatibility evidence digest is not canonical",
        )
        .with_context("field", field));
    }
    Ok(value.to_owned())
}

fn require_equal(failures: &mut Vec<String>, field: &str, actual: &str, expected: &str) {
    if actual != expected {
        failures.push(format!("{field}:unexpected"));
    }
}

fn require_true(failures: &mut Vec<String>, field: &str, value: bool) {
    if !value {
        failures.push(format!("{field}:not_observed"));
    }
}

fn require_zero(failures: &mut Vec<String>, field: &str, value: u32) {
    if value != 0 {
        failures.push(format!("{field}:residual:{value}"));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const DIGEST_A: &str =
        "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    const DIGEST_B: &str =
        "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";

    fn canonical_subject() -> String {
        format!(
            concat!(
                "format=eva.mcp-compatibility.v1\n",
                "evidence_kind=measurement\n",
                "server_name=eva\n",
                "server_version={}\n",
                "protocol_version=2025-11-25\n",
                "transport=streamable_http\n",
                "tls_handshake_completed=true\n",
                "tls_peer_name=127.0.0.1\n",
                "tls_protocol=TLSv1_3\n",
                "tls_handshake_count=6\n",
                "tool_name=compat.echo\n",
                "schema_sha256={}\n",
                "schema_bytes=128\n",
                "output_sha256={}\n",
                "output_bytes=64\n",
                "initialize_server_info_observed=true\n",
                "tools_list_schema_observed=true\n",
                "tools_call_result_observed=true\n",
                "abort_socket_closed=true\n",
                "abort_session_deleted=true\n",
                "abort_reader_joined=true\n",
                "abort_sessions_after=0\n",
                "abort_readers_after=0\n",
                "abort_cleanup_pending_after=0\n"
            ),
            env!("CARGO_PKG_VERSION"),
            DIGEST_A,
            DIGEST_B,
        )
    }

    #[test]
    fn canonical_measurement_parses_and_verifies() {
        let subject = canonical_subject();
        let evidence = ReleaseMcpCompatibilityEvidence::parse_manifest(&subject).unwrap();

        assert_eq!(evidence.to_manifest(), subject);
        let report = evidence.verify();
        assert_eq!(report.status, "verified");
        assert!(report.failures.is_empty());
    }

    #[test]
    fn sealed_runtime_measurement_matches_the_release_subject_contract() {
        let measurement = eva_mcp::McpCompatibilityMeasurement::measure_loopback().unwrap();
        let subject = std::str::from_utf8(measurement.subject_bytes()).unwrap();
        let evidence = ReleaseMcpCompatibilityEvidence::parse_manifest(subject).unwrap();

        assert_eq!(
            evidence.to_manifest().as_bytes(),
            measurement.subject_bytes()
        );
        assert_eq!(evidence.verify().status, "verified");
    }

    #[test]
    fn fixture_kind_cannot_claim_the_measurement_subject_contract() {
        let subject =
            canonical_subject().replace("evidence_kind=measurement\n", "evidence_kind=fixture\n");
        let evidence = ReleaseMcpCompatibilityEvidence::parse_manifest(&subject).unwrap();

        assert_eq!(evidence.verify().status, "blocked");
        assert!(evidence
            .verify()
            .failures
            .contains(&"evidence_kind:unexpected".to_owned()));
    }

    #[test]
    fn all_true_observations_still_block_nonzero_abort_residuals() {
        let subject = canonical_subject().replace(
            "abort_cleanup_pending_after=0\n",
            "abort_cleanup_pending_after=1\n",
        );
        let evidence = ReleaseMcpCompatibilityEvidence::parse_manifest(&subject).unwrap();
        let report = evidence.verify();

        assert_eq!(report.status, "blocked");
        assert!(report
            .failures
            .contains(&"abort_cleanup_pending_after:residual:1".to_owned()));
    }

    #[test]
    fn handshake_count_requires_observation_without_freezing_connection_count() {
        let one_handshake =
            canonical_subject().replace("tls_handshake_count=6\n", "tls_handshake_count=1\n");
        let one = ReleaseMcpCompatibilityEvidence::parse_manifest(&one_handshake).unwrap();
        assert_eq!(one.verify().status, "verified");

        let no_handshake =
            canonical_subject().replace("tls_handshake_count=6\n", "tls_handshake_count=0\n");
        let zero = ReleaseMcpCompatibilityEvidence::parse_manifest(&no_handshake).unwrap();
        let report = zero.verify();
        assert_eq!(report.status, "blocked");
        assert!(report
            .failures
            .contains(&"tls_handshake_count:empty".to_owned()));
    }

    #[test]
    fn parser_rejects_noncanonical_order_digest_and_line_endings() {
        let subject = canonical_subject();
        assert!(
            ReleaseMcpCompatibilityEvidence::parse_manifest(&subject.replacen(
                "server_name=eva\nserver_version=",
                "server_version=",
                1
            ))
            .is_err()
        );
        assert!(ReleaseMcpCompatibilityEvidence::parse_manifest(
            &subject.replace(DIGEST_A, "sha256:ABC")
        )
        .is_err());
        assert!(
            ReleaseMcpCompatibilityEvidence::parse_manifest(&subject.replace('\n', "\r\n"))
                .is_err()
        );
    }
}
